(*
 *  Translator for SCICOS
 *
 *  Copyright (C) 2005 - 2007 Imagine S.A.
 *  For more information or commercial use please contact us at www.amesim.com
 *
 *  This program is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU General Public License
 *  as published by the Free Software Foundation; either version 2
 *  of the License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

 *)

(** Set the actual svn last update date and version.
  This file is automatically generated from the file versiondate.ml.tmpl.
  The last is copied and transformed using a sed command, that will replace
  the values (AUTO_UPDATE_DATE and AUTO_UPDATE_REV) of the variables
  auto_updated_date and auto_updated_rev with the actual SVN last update date
  and version. Lines which set the variables auto_updated_date and auto_updated_rev
  must be kept as they are (unless you want to change the sed command).

  On computers that doesn't have svn grep or sed you can simply copy
  the file versiondate.ml.tmpl to versiondate.ml and modify it if you like.

@author AJN
@since 20/02/2008.
*)

val print_versiondate : unit -> unit
