#######################################################################
#                                                                     #
#                           Modelicac                                 #
#                                                                     #
#  Copyright 2010-2016,                                               #
#  Institut National de Recherche en Informatique et en Automatique.  #
#  All rights reserved.                                               #
#                                                                     #
#  This file is distributed under the terms of the BSD License.       #
#                                                                     #
#######################################################################

SHELL=/bin/sh

all:
	dune build

clean:

distclean: clean
	$(RM) -fr _build
