type token =
  | IDENT of (string)
  | UNSIGNED_INTEGER of (string)
  | UNSIGNED_NUMBER of (string)
  | STRING of (string)
  | MODEL_TAG
  | MODEL_END_TAG
  | NAME_TAG
  | NAME_END_TAG
  | ELEMENTS_TAG
  | ELEMENT_STRUCT_TAG
  | ELEMENT_STRUCT_SUBNODES_TAG
  | ELEMENT_STRUCT_SUBNODES_END_TAG
  | ELEMENT_STRUCT_END_TAG
  | ELEMENT_TERMINAL_TAG
  | ELEMENT_TERMINAL_KIND_TAG
  | ELEMENT_TERMINAL_KIND_END_TAG
  | ELEMENT_TERMINAL_ID_TAG
  | ELEMENT_TERMINAL_ID_END_TAG
  | ELEMENT_TERMINAL_END_TAG
  | ELEMENTS_END_TAG
  | EQUATIONS_TAG
  | EQUATIONS_END_TAG
  | WHEN_CLAUSES_TAG
  | WHEN_CLAUSES_END_TAG
  | ELEMENT_TERMINAL_OUTPUT_TAG
  | ELEMENT_TERMINAL_SELECT_TAG
  | ELEMENT_TERMINAL_COMMENT_VALUE_TAG of (string)
  | ELEMENT_TERMINAL_INITIAL_VALUE_VALUE_TAG of (string)
  | ELEMENT_TERMINAL_NOMINAL_VALUE_VALUE_TAG of (string)
  | ELEMENT_TERMINAL_FIXED_VALUE_TAG of (string)
  | EQUATION_VALUE_TAG of (string)
  | WHEN_CLAUSE_VALUE_TAG of (string)
  | ERROR
  | EOF

val xML_definition_eof :
  (Lexing.lexbuf  -> token) -> Lexing.lexbuf -> XMLTree.t
